텐서는 자동 미분에 최적화되어 있음

In [1]:
import torch 
import numpy as np

# 텐서 초기화

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
x_ones = torch.ones_like(x_data) # x_data의 속성 유지
print("Ones Tensor: {}".format(x_ones))

x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성을 덮어씀
print("Random Tensor: {}".format(x_rand))

Ones Tensor: tensor([[1, 1],
        [1, 1]])
Random Tensor: tensor([[0.3113, 0.2848],
        [0.7882, 0.6646]])


무작위 또는 상수 값을 사용하기 <br>
shape은 텐서의 차원을 나타내는 튜플로, 아래 함수들에서는 출력 텐서의 차원을 결정

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6991, 0.1744, 0.9879],
        [0.8867, 0.7868, 0.9858]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 텐서의 속성

In [8]:
tensor = torch.rand(3, 4)

print("Shape of tensor: {}".format(tensor.shape))
print("Datatype of tensor: {}".format(tensor.dtype))
print("Device tensor: {}".format(tensor.device))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor: cpu


# 텐서 연산

In [11]:
# 학습에 사용할 CPU나 GPU 장치 얻기
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)

# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to(device)

넘파이 식의 표준 인덱싱과 슬라이싱

In [12]:
tensor = torch.ones(4, 4)
print("First row: {}".format(tensor[0]))
print("First column: {}".format(tensor[:, 0]))
print("Last column: {}".format(tensor[:, -1]))
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


텐서 합치기

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


산술연산

In [16]:
# 두 텐서 간의 행렬 곱(matrix multipication)을 계산. y1, y2, y3은 모두 같은 값을 가짐 
# tensor.T << 텐서의 전치를 반호나

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)

# 요소별 곱(element-wise product)을 계산. z1, z2, z3는 모두 같은 값을 가짐
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


단일-요소 (Single-element) 텐서: 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 파이썬 숫자 값으로 변환 가능

In [19]:
agg = tensor.sum()
print("agg : \n{} \t tpye : {}\n".format(agg, type(agg)))

agg_item = agg.item()
print(agg_item, type(agg_item))

agg : 
12.0 	 tpye : <class 'torch.Tensor'>

12.0 <class 'float'>


바꿔치기(in-place) 연산 <br>
연산 결과를 피연산자(operand)에 저장하는 연산

In [20]:
print("{}\n".format(tensor))
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


바꿔치기 연산은 메모리를 일부 절약하지만, 기록이 즉시 삭제되어 도함수 계산에 문제가 발생

# 넘파이 변환 (Bridge)

텐서를 넘파이 배열로 변환

In [22]:
t = torch.ones(5)
print("t: {}".format(t))

n = t.numpy()
print("n: {}".format(n))

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 넘파이 배열에 반영

In [23]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [24]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


넘파이 배열을 텐서로 변환하기

In [25]:
n = np.ones(5)
t = torch.from_numpy(n)

넘파이 배열의 변경사항이 텐서에 반영

In [26]:
np.add(n, 1, out = n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
