# 텐서

텐서는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구죠 <BR>
Pytorch에서는 텐서를 사용하여 모델의 입력과 출력뿐만 아니라 모델의 매개변수를 부호화(encode)할 수 있다. <Br>
텐서는 GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다

In [1]:
import torch
import numpy as np

# 텐서 초기화 하기

## 데이터로부터 직접(directly) 생성하기

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

## Numpy 배열로부터 생성하기

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

## 다른 텐서로부터 생성하기

In [6]:
# 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양, 자료형)을 유지

x_ones = torch.ones_like(x_data)
print('Ones Tensor: \n {}\n'.format(x_ones))

x_rand = torch.rand_like(x_data, dtype = torch.float)
print('Random Tensor: \n {} \n'.format(x_rand))

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.0331, 0.0496],
        [0.3074, 0.9349]]) 



## 무작위(random) 또는 상수(constant) 값을 사용하기

shape은 텐서의 차원(dimension)을 나타내는 튜플로, 아래 함수들에서는 출력텐서들의 차원을 결정

In [7]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print('Random Tensor: \n {} \n '.format(rand_tensor))
print('Ones Tensor: \n {} \n '.format(ones_tensor))
print('Zeros Tensor: \n {} \n '.format(zeros_tensor))

Random Tensor: 
 tensor([[0.1949, 0.5921, 0.7077],
        [0.4798, 0.2470, 0.3002]]) 
 
Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 


# 텐서의 속성

텐서의 속성은 텐서의 모양, 자료형 및 어느 장치에 저장되는지를 나타낸다

In [9]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 텐서 연산 (Operation)

전치(Transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등 100가지 이상 텐서 연산 가능

In [10]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print('Device tensor is sotred on : {}'.format(tensor.device))

Device tensor is sotred on : cuda:0


## Numpy 식의 표준 인덱싱과 슬라이싱

In [11]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 텐서 합치기

torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결 가능

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:
t2 = torch.cat([tensor, tensor], dim = 0)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 텐서 곱하기

In [19]:
tensor = torch.rand(2, 4)

# 요소별 곱(element-wise product)을 계산
print('tensor.mul(tensor) \n {} \n'.format(tensor.mul(tensor)))

# 다른 문법:
print('tensor * tensor: \n {} \n'.format(tensor*tensor))

tensor.mul(tensor) 
 tensor([[0.1472, 0.7384, 0.5977, 0.0525],
        [0.6079, 0.6963, 0.5509, 0.1353]]) 

tensor * tensor: 
 tensor([[0.1472, 0.7384, 0.5977, 0.0525],
        [0.6079, 0.6963, 0.5509, 0.1353]]) 



두 텐서간의 행렬 곱(Matrix Multiplication)을 계산

In [20]:
print('tensor.matmul(tensor.T): \n {} \n'.format(tensor.matmul(tensor.T)))
# 다른 문법 :
print('tensor @ tensor.T: \n {} \n'.format(tensor @ tensor.T))

tensor.matmul(tensor.T): 
 tensor([[1.5360, 1.6744],
        [1.6744, 1.9904]]) 

tensor @ tensor.T: 
 tensor([[1.5360, 1.6744],
        [1.6744, 1.9904]]) 



## 바꿔치기 (in-place) 연산ㅡ

In [24]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.3837, 0.8593, 0.7731, 0.2292],
        [0.7797, 0.8345, 0.7422, 0.3678]]) 

tensor([[5.3837, 5.8593, 5.7731, 5.2292],
        [5.7797, 5.8345, 5.7422, 5.3678]])


# Numpy 변환 (Bridge)

CPU 상의 텐서와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경

## 텐서를 Numpy 배열로 변환하기

In [27]:
t = torch.ones(5)
print('t : {}'.format(t))

n = t.numpy()
print('n: {} \n'.format(n))

t : tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.] 



텐서의 변경사항이 Numpy 배열에 반영

In [28]:
t.add_(1) # inplace 연산
print('t: {} \n'.format(t))
print('n: {} \n'.format(n))

t: tensor([2., 2., 2., 2., 2.]) 

n: [2. 2. 2. 2. 2.] 



# Numpy 배열을 텐서로 변환하기

In [29]:
n = np.ones(5)
t = torch.from_numpy(n)

Numpy 배열의 변경 사항이 텐서에 반영

In [30]:
np.add(n, 1, out = n)
print('t: {} \n'.format(t))
print('n: {} \n'.format(n))

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64) 

n: [2. 2. 2. 2. 2.] 

