# TORCH.AUTOGRAD에 대한 간단한 소개

torch.autograd는 신경망 학습을 지원하는 Pytorch의 자동 미분 엔진

In [3]:
import torch
from torchvision.models import resnet18
model = resnet18(pretrained = True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [4]:
data

tensor([[[[0.9064, 0.3485, 0.2381,  ..., 0.1767, 0.7614, 0.6663],
          [0.7171, 0.5173, 0.8699,  ..., 0.1794, 0.0817, 0.0664],
          [0.0311, 0.5150, 0.2388,  ..., 0.9915, 0.1352, 0.9187],
          ...,
          [0.9934, 0.8914, 0.3213,  ..., 0.0584, 0.5041, 0.1237],
          [0.8765, 0.0412, 0.3193,  ..., 0.9786, 0.0091, 0.8778],
          [0.4133, 0.4740, 0.6003,  ..., 0.6430, 0.1898, 0.9862]],

         [[0.1610, 0.2959, 0.5990,  ..., 0.4790, 0.6719, 0.1364],
          [0.5662, 0.9573, 0.6051,  ..., 0.5597, 0.2268, 0.9320],
          [0.5470, 0.5032, 0.3032,  ..., 0.3970, 0.4742, 0.5091],
          ...,
          [0.5235, 0.0165, 0.8715,  ..., 0.0747, 0.2004, 0.4905],
          [0.6804, 0.1238, 0.2182,  ..., 0.3470, 0.4157, 0.1173],
          [0.4524, 0.2889, 0.9604,  ..., 0.6243, 0.9729, 0.4206]],

         [[0.7879, 0.0636, 0.3488,  ..., 0.3200, 0.8117, 0.2459],
          [0.9572, 0.6710, 0.0406,  ..., 0.2466, 0.3515, 0.3245],
          [0.1799, 0.5977, 0.0636,  ..., 0

In [5]:
labels

tensor([[2.8809e-01, 2.7920e-01, 4.3784e-01, 8.8233e-01, 3.4885e-02, 8.5637e-01,
         6.3315e-01, 2.7684e-01, 7.8363e-01, 2.8573e-01, 2.6013e-01, 4.0930e-01,
         4.5156e-01, 3.2747e-01, 3.0821e-02, 8.2870e-01, 5.3698e-01, 5.1117e-01,
         6.5098e-02, 4.0102e-04, 6.0474e-01, 8.4908e-01, 5.3313e-01, 8.4473e-01,
         3.2569e-01, 8.2822e-01, 8.6874e-01, 5.9652e-01, 8.5032e-01, 6.6667e-01,
         6.8588e-01, 6.2696e-01, 5.8921e-01, 5.4941e-01, 4.3337e-01, 1.7793e-01,
         2.4953e-01, 8.5544e-02, 3.1036e-01, 6.9300e-01, 8.7660e-01, 2.1501e-01,
         1.2344e-01, 2.7403e-01, 5.3743e-01, 7.4585e-01, 5.5175e-01, 1.7558e-01,
         2.9179e-01, 6.2447e-01, 4.4776e-01, 4.6835e-01, 9.1756e-01, 6.4319e-01,
         9.8232e-01, 4.2696e-01, 3.3161e-01, 7.0290e-01, 3.9135e-01, 3.9929e-01,
         9.1297e-01, 6.9357e-01, 7.4171e-02, 8.8492e-02, 7.2215e-01, 8.7687e-01,
         8.8984e-02, 6.9845e-01, 9.7054e-01, 7.9938e-01, 1.2834e-02, 1.9401e-01,
         8.1550e-01, 9.8131e

In [6]:
# 순전파 단계: 입력 데이터를 모델의 각 층(layer)에 통과시켜 예측값 생성
prediction = model(data)

In [7]:
prediction

tensor([[-2.5684e-01, -3.9069e-01, -1.9851e-01, -1.2658e+00, -6.0695e-01,
         -2.2197e-01, -2.7030e-01,  5.5385e-01,  4.3437e-01, -1.0194e+00,
         -9.4547e-01, -5.9536e-01, -3.0485e-01, -8.8255e-01, -1.1131e+00,
         -8.2888e-01, -1.0252e+00, -1.4781e-01, -3.7930e-01, -4.5417e-01,
         -1.4519e+00, -7.7934e-01, -1.3311e+00,  1.1196e-01, -7.4696e-01,
         -1.2647e+00, -1.1200e+00, -1.4658e+00, -9.8608e-01, -1.5868e-01,
         -6.6170e-01, -8.9973e-01, -6.1620e-01, -2.9427e-01,  1.3997e-02,
         -2.7353e-01,  6.3709e-01, -7.5204e-01, -6.6652e-01,  1.7317e-01,
         -8.6153e-01, -9.1905e-01, -1.0584e+00, -2.0599e-01, -6.2772e-01,
         -3.4088e-01, -8.6603e-01, -2.6073e-01, -1.0382e+00, -6.5071e-01,
         -1.3019e-03,  7.3717e-01, -5.1810e-01, -8.7423e-01, -6.1870e-02,
         -1.0192e+00, -7.6636e-01, -1.4583e+00, -4.2244e-01, -4.6407e-01,
          6.5452e-01, -7.2659e-02,  3.3189e-03,  1.0196e-01, -6.4950e-01,
         -1.4872e-01, -2.3207e-01, -8.

In [8]:
# 역전파 
loss = (prediction - labels).sum()
loss.backward()

In [9]:
optim = torch.optim.SGD(model.parameters(), lr = 1e-2, momentum=0.9)

In [10]:
#.step 함수를 호출하여 경사하강법을 시작.
optim.step()